require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
require "user.commands"

spec "user.colorscheme"
spec "user.mini-icons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.telescope"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.neotest"
spec "user.autopairs"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.bufferline"
spec "user.autotag"
spec "user.cmp"
spec "user.none-ls"

-- Extras
spec "user.extras.fidget"
spec "user.extras.neoscroll"
spec "user.extras.rainbow-delimiters"
spec "user.extras.todo-comments"
spec "user.extras.typescript-tools"
spec "user.extras.live-server"
spec "user.extras.dadbod-ui"
spec "user.extras.markdown-preview"
spec "user.extras.oil"
spec "user.extras.zen"
spec "user.extras.colorizer"
spec "user.extras.scrollbar"
spec "user.extras.marks"
spec "user.extras.ufo"
-- spec "user.extras.hipatterns" -- cause stuttering in large files
-- spec "user.extras.copilot"
-- spec "user.extras.faster"
-- spec "user.extras.gemini"

require "user.lazy"
