require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
require "user.commands"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.neotest"
spec "user.autopairs"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.bufferline"

-- Extras
spec "user.extras.colorizer"
spec "user.extras.fidget"
spec "user.extras.rainbow-delimiters"
spec "user.extras.neoscroll"
spec "user.extras.todo-comments"
spec "user.extras.scrollbar"

require "user.lazy"

-- ffmpeg -hwaccel nvdec -y -i 2023-12-02\ 18-19-44.mp4 -c:v nvenc -qp 18 -preset hq -profile:v high -c:a copy out.mkv
